// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'event.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'event.g.dart';

@freezed
class Event with _$Event {
  const factory Event({
    int? id,
    String? title,
    String? description,
    String? onlineUrl,
    List<String>? additionalUrls,
    List<String>? accessibility,
    String? eventCategory,
    String? address,
    List<String>? images,
    List<String>? keywords,
    int? maxAttendees,
    String? registrationDeadline,
    String? startDate,
    String? endDate,
    String? location,
    double? lat,
    double? lng,
    String? city,
    String? state,
    String? country,
    String? priceCountry,
    int? price,
    String? createdAt,
    String? updatedAt,
    int? userId,
    dynamic cCount,
  }) = _Event;

  factory Event.fromJson(Map<String, dynamic> json) => _$EventFromJson(json);
}
